Implement the /models endpoint for the VLLM provider
For some reason, continue in JetBrains needs this otherwise loading the
plugin fails with:
```
Error: HTTP 404 Not Found from http://127.0.0.1:8000/vllm/models

This may mean that you forgot to add '/v1' to the end of your 'apiBase'
in config.json.
    at customFetch (/snapshot/continue/binary/out/index.js:471442:17)
        at process.processTicksAndRejections
        (node:internal/process/task_queues:95:5)
            at async withExponentialBackoff
            (/snapshot/continue/binary/out/index.js:471175:22)
---> continue restarts here
[info] Starting Continue core...
[2024-12-04T08:52:45] [info] Starting Continue core...
```